services:
  kurage:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VHS_VER=0.10.0
        - TTYD_VER=1.7.7
        - WORKDIR=/kurage
    working_dir: /kurage
    volumes:
      - ./:/kurage
      - kurage_node_modules:/kurage/node_modules
      - kurage_bun_cache:/root/.bun
      - kurage_deno_cache:/root/.cache/deno
    environment:
      - TZ=Asia/Tokyo

volumes:
  kurage_node_modules:
  kurage_bun_cache:
  kurage_deno_cache:
